/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package srds.s9

class App {
    val greeting: String
        get() {
            return "Nie, nie powiem tego."
        }
}

fun main() {
    println(App().greeting)
}
